### ISSUE TITLE
Remove useless class attribute from DAV requests

### ISSUE THREAD

**Issue by unnivm** [bitfireAT/davdroid#615]
Hi,

I am getting request with a new element like below:

```
<CD:addressbook-description xmlns:CD="urn:ietf:params:xml:ns:carddav"/>
<current-user-privilege-set class="java.util.LinkedList"/>
``````

I was able to get information about ```<current-user-privilege-set>``` , but not  ```class="java.util.LinkedList"/,```

What exactly class attribute is trying to achieve here.

Please find my response xml in this case:

```
HTTP/1.1 207 Multi-Status
Date: Thu Aug 20 21:53:04 IST 2015
Server: Test
DAV:1, 3, extended=mkcol, addressbook
Content-Length: 659
Content-Type: text/xml; charset=UTF-8

<?xml version="1.0" encoding="utf-8"?><d:multistatus xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/bt/admin/</d:href><d:propstat><d:prop><CD:addressbook-description xmlns:CD="urn:ietf:params:xml:ns:carddav">My address Book</CD:addressbook-description><d:current-user-privilege-set class="java.util.LinkedList"><d:privilege><d:read></d:read></d:privilege></d:current-user-privilege-set><d:displayname>My address Book</d:displayname><d:resourcetype><d:collection>abc</d:collection></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
``````
Thank you,
Unni

**Comment by untitaker** [comment]
@unnivm Your post got scrambled because you didn't put \``` around your codeblocks.

**Comment by unnivm** [comment]
sorry, I did not know this feature. I have corrected it. Thank you

**Comment by untitaker** [comment]
I think you're still missing some stuff after your first sentence.

**Comment by unnivm** [comment]
I have corrected it.  I just pasted only two lines of XML at the beginning of the topic. Please let me know if I miss anything

**Comment by untitaker** [comment]
Ah yes, I believe I've observed the same glitch one time. You can ignore that attribute.

**Comment by unnivm** [comment]
OK, I have just ignored this attribute. Initially I was bit confused as how
to use this attribute. Now you can *close* this item.


Thank you,

Unni



On Fri, Aug 21, 2015 at 1:46 AM, Markus Unterwaditzer <
notifications@github.com> wrote:

> Ah yes, I believe I've observed the same glitch one time. You can ignore
> that attribute.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitfireAT/davdroid/issues/615#issuecomment-133158636>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by untitaker** [comment]
Devv4ever, what is the reason for DavDroid sending the class attribute?

On 21 August 2015 13:07:41 CEST, devvv4ever <notifications@github.com> wrote:
>Closed #615.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/615#event-388683216

-- 
Sent from my phone. Please excuse my brevity.

**Comment by devvv4ever** [comment]
Untitaker: no special reason. It's just an artifact of SimpleXML. It should be ignored by the server, normally. If you know how to remove it we're happy for a pull request ;-)

**Comment by phy25** [comment]
Some hints: http://stackoverflow.com/questions/17391184/removing-xml-java-class-attribute-from-simplexml-code

**Comment by unnivm** [comment]
is there any schema for all these requests? In fact I was searching for in
the repository sometime back to understand the request xml

On Tue, Aug 25, 2015 at 9:09 AM, Phy <notifications@github.com> wrote:

> Some hints:
> http://stackoverflow.com/questions/17391184/removing-xml-java-class-attribute-from-simplexml-code
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitfireAT/davdroid/issues/615#issuecomment-134465028>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by rfc2822** [comment]
> is there any schema for all these requests? In fact I was searching for in the repository sometime back to understand the request xml

What do you mean by schema? The requests are defined in the RFCs, the code is in https://github.com/bitfireAT/davdroid/tree/master/app/src/main/java/at/bitfire/davdroid/webdav in dav*, especially DavProp
